[package]
name = "stun-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stun-rs = { path = "../stun-rs" }
log = "0.4.21"
bytes = "1.6.0"

[dev-dependencies]
env_logger = "0.11.3"