[package]
name = "stun-vectors"
version = "0.1.0"
authors = ["Santiago Carot-Nemesio <sancane@gmail.com"]
edition = "2021"

[dependencies]

[dev-dependencies]
stun-rs = { path = "../stun-rs", features = ["experiments", "ice", "turn"] }
