name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with experiments
      run: cargo build --package stun-rs --features experiments --verbose
    - name: Build with turn
      run: cargo build --package stun-rs --features turn --verbose
    - name: Build with ice
      run: cargo build --package stun-rs --features ice --verbose
    - name: Build with mobility
      run: cargo build --package stun-rs --features mobility --verbose
    - name: Build with discovery
      run: cargo build --package stun-rs --features discovery --verbose
    - name: Build with all features
      run: cargo build --verbose --all-features
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run tests
      run: cargo test --verbose --all-features

  cargo_check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cargo-sort
      run: cargo install --locked cargo-sort
    - run: cargo sort -w -c

  spellcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-spellcheck

    - uses: actions/checkout@v3

    - name: Run cargo spellcheck
      run: cargo-spellcheck --code 1 --cfg=.github/workflows/spellchecker.cfg
